"""Deterministic ASS (Advanced SubStation Alpha) subtitle generator.

Generates precise subtitle tracks from timeline word-timing groups and
safe-zone coordinates. Pure Python, no external dependencies.
"""
from __future__ import annotations

from typing import Any


def sec_to_ass_time(sec: float) -> str:
    """Format seconds into ASS timestamp format: H:MM:SS.cc."""
    sec = max(0.0, float(sec))
    hours = int(sec // 3600)
    remainder = sec % 3600
    minutes = int(remainder // 60)
    seconds = remainder % 60
    secs_int = int(seconds)
    centis = int(round((seconds - secs_int) * 100))
    if centis >= 100:
        centis -= 100
        secs_int += 1
        if secs_int >= 60:
            secs_int -= 60
            minutes += 1
            if minutes >= 60:
                minutes -= 60
                hours += 1
    return f"{hours}:{minutes:02d}:{secs_int:02d}.{centis:02d}"


def calculate_safe_zone_margins(safe_zone: dict[str, float] | tuple[float, float, float, float] | None,
                               canvas_w: int = 1920,
                               canvas_h: int = 1080) -> tuple[int, int, int]:
    """Calculate (MarginL, MarginR, MarginV) in pixels from normalized safe zone."""
    if isinstance(safe_zone, dict):
        zx = float(safe_zone.get("x", 0.05))
        zy = float(safe_zone.get("y", 0.84))
        zw = float(safe_zone.get("width", 0.90))
        zh = float(safe_zone.get("height", 0.15))
    elif isinstance(safe_zone, (tuple, list)) and len(safe_zone) >= 4:
        zx, zy, zw, zh = safe_zone[:4]
    else:
        zx, zy, zw, zh = 0.05, 0.84, 0.90, 0.15

    margin_l = int(round(zx * canvas_w))
    margin_r = int(round((1.0 - (zx + zw)) * canvas_w))
    # Bottom margin from bottom edge of canvas
    margin_v = int(round((1.0 - (zy + zh)) * canvas_h)) + 20
    return max(0, margin_l), max(0, margin_r), max(0, margin_v)


def escape_ass_text(text: str) -> str:
    """Escape text for safe literal inclusion in ASS Dialogue lines.

    Maintains visible typography and Unicode text fidelity while preventing
    ASS override tag injection:
    - Real line breaks (\\r\\n, \\r, \\n) are converted to ASS hard breaks '\\N'.
    - Literal backslashes before N/n/h (e.g. \\notes, \\help) are protected with zero-width
      spacing so they render as literal backslashes without triggering unwanted ASS breaks.
    - Other literal backslashes (e.g. C:\\Windows) remain pure literal '\\'.
    - Curly braces '{' and '}' are mapped to typographic small curly brackets U+FE5B / U+FE5C
      which preserve normal proportional character width (preventing wide fullwidth gaps)
      while preventing ASS override tag parsing.
    - Preserves all Unicode characters, Vietnamese diacritics, and punctuation.
    """
    if not text:
        return ""
    import re
    escaped = text.replace("\r\n", "\n").replace("\r", "\n")
    escaped = re.sub(r"\\([Nnh])", lambda m: f"\\\u200b{m.group(1)}", escaped)
    escaped = escaped.replace("{", "\ufe5b").replace("}", "\ufe5c")
    escaped = escaped.replace("\n", "\\N")
    return escaped


def generate_subtitles_ass(timeline_data: dict[str, Any],
                           safe_zone: dict[str, float] | tuple[float, float, float, float] | None = None,
                           canvas: dict[str, Any] | None = None) -> str:
    """Generate a complete, deterministic ASS subtitle script from timeline data."""
    canvas_info = canvas or timeline_data.get("canvas", {})
    canvas_w = int(canvas_info.get("width", 1920))
    canvas_h = int(canvas_info.get("height", 1080))

    sz = safe_zone or timeline_data.get("subtitle_safe_zone")
    margin_l, margin_r, margin_v = calculate_safe_zone_margins(sz, canvas_w, canvas_h)

    script_info = [
        "[Script Info]",
        "; Script generated by vidtool AI Editorial Director",
        "ScriptType: v4.00+",
        f"PlayResX: {canvas_w}",
        f"PlayResY: {canvas_h}",
        "WrapStyle: 0",
        "ScaledBorderAndShadow: yes",
        "",
    ]

    styles = [
        "[V4+ Styles]",
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding",
        # Default style: High-legibility documentary subtitles (white text, subtle dark outline, soft shadow, bottom-center)
        f"Style: Default,DejaVu Sans,42,&H00FFFFFF,&H000000FF,&H00101010,&H80000000,-1,0,0,0,100,100,0,0,1,3,1,2,{margin_l},{margin_r},{margin_v},1",
        # NodeLabel: For text-only nodes (badges/labels) centered inside their placement
        "Style: NodeLabel,DejaVu Sans,26,&H00F9FAFB,&H000000FF,&H00141619,&H90000000,-1,0,0,0,100,100,0,0,1,2,1,5,10,10,10,1",
        # NodeQuote: For archival quotes / documents (italic, crisp light text)
        "Style: NodeQuote,DejaVu Sans,28,&H00F9FAFB,&H000000FF,&H00141619,&H90000000,0,-1,0,0,100,100,0,0,1,2,1,5,10,10,10,1",
        # NodeTimeline: For chronological timeline entries (Vox Yellow in BGR)
        "Style: NodeTimeline,DejaVu Sans,24,&H0000D1FF,&H000000FF,&H00141619,&H90000000,-1,0,0,0,100,100,0,0,1,2,1,5,10,10,10,1",
        "",
    ]

    events = [
        "[Events]",
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
    ]

    subtitles = timeline_data.get("subtitles", [])
    for sub in subtitles:
        start_t = sec_to_ass_time(sub["start_sec"])
        end_t = sec_to_ass_time(sub["end_sec"])
        text = escape_ass_text(sub.get("text", ""))
        events.append(f"Dialogue: 0,{start_t},{end_t},Default,,0,0,0,,{text}")

    return "\n".join(script_info + styles + events) + "\n"


def generate_node_text_dialogue(text: str, start_sec: float, end_sec: float,
                                center_x_px: int, center_y_px: int,
                                style_name: str = "NodeLabel") -> str:
    """Generate an ASS Dialogue line positioned at explicit pixel coordinates."""
    start_t = sec_to_ass_time(start_sec)
    end_t = sec_to_ass_time(end_sec)
    clean_text = escape_ass_text(text)
    # \an5 positions anchor at center; \pos(cx, cy) places center at specified coordinates
    pos_tag = f"{{\\an5\\pos({center_x_px},{center_y_px})}}"
    return f"Dialogue: 1,{start_t},{end_t},{style_name},,0,0,0,,{pos_tag}{clean_text}"
